module.exports = {
    Detour: require("./detour"),
    Base: require("./base"),
    VR: require("./vr"),
    UID: require("./uid"),
    Tag: require("./tag"),
    Lookup: require("./lookup"),
    TagPath: require("./tag-path"),
    TagTree: require("./tag-tree"),
    Parts: require("./parts"),
    CharacterSets: require("./character-sets"),
    Sources: require("./sources"),
    Flows: require("./flows"),
    Sinks: require("./sinks"),
    DicomParser: require("./dicom-parser"),
    DicomFlow: require("./dicom-flow"),
    DicomFlows: require("./dicom-flows"),
    CollectFlow: require("./collect-flow"),
    ModifyFlow: require("./modify-flow"),
    Value: require("./value"),
    Elements: require("./elements"),
    ElementFlows: require("./element-flows"),
    ElementSink: require("./element-sink"),
    pipe: require("multipipe")
};
